### ISSUE TITLE
Runtime.ImportModuleError: Error: Cannot find module '@aws-sdk/client-secrets-manager'

### ISSUE THREAD

**Issue by robertd** [willdady/cdk-iam-credentials-rotator#1]
Hi @willdady. I keep getting `Runtime.ImportModuleError: Error: Cannot find module '@aws-sdk/client-secrets-manager` when running `HandlerCredentials`.

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/31543/161344650-3bbc2687-d992-4913-b58b-c67feac71bd4.png">

Do you happen to have a working example or a blog post or something? Thanks in advance.

**Comment by willdady** [comment]
Hi @robertd. Assuming you have copied the template from the README you will need to install `@aws-sdk/client-secrets-manager` and any other dependencies your handler function imports.

**Comment by robertd** [comment]
Howdy. I did install the dependencies... but I'm still getting that error. Do you happen to have an example repo?

```json
{
  "name": "iam-users-factory",
  "version": "0.1.0",
  "bin": {
    "iam-keys-factory": "bin/iam-users-factory.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@types/jest": "^26.0.10",
    "@types/node": "^10.17.27",
    "aws-cdk": "2.19.0",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-sdk/client-secrets-manager": "^3.58.0",
    "aws-cdk-lib": "2.19.0",
    "cdk-iam-credentials-rotator": "^1.4.0",
    "constructs": "^10.0.0",
    "source-map-support": "^0.5.16"
  }
}
```

**Comment by willdady** [comment]
I don't have a publicly shared example but here the `package.json` from a repo I use to test this construct.

```json
{
  "name": "cdk-iam-credentials-rotator-test",
  "version": "0.1.0",
  "bin": {
    "cdk-iam-credentials-rotator-test": "bin/cdk-iam-credentials-rotator-test.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "2.17.0",
    "esbuild": "0",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-sdk/client-secrets-manager": "^3.58.0",
    "aws-cdk-lib": "2.17.0",
    "cdk-iam-credentials-rotator": "^1.4.0",
    "constructs": "^10.0.0",
    "source-map-support": "^0.5.16"
  }
}
```

Closing as this sounds like an issue external to the construct.

**Comment by robertd** [comment]
Hmm... I'm still stuck. IMHO having a working example would be very beneficial for the construct.
