### ISSUE TITLE
[question] initial credential rotation

### ISSUE THREAD

**Issue by robertd** [willdady/cdk-iam-credentials-rotator#5]
@willdady How do you trigger that initial credential rotation if your schedule is i.e 7 days? This works great for short term keys, but what about mid/long term keys (days/weeks/months)? In that case the initial key creation will take days/weeks/months, right?Thanks.

**Comment by willdady** [comment]
Hi @robertd. You can trigger this manually by simply invoking the Lambda function which is normally triggered by the EventBridge rule. Refer to the architecture diagram at the bottom of the README.

**Comment by robertd** [comment]
@willdady I've tried triggering the function with EventBridge trigger (description: `Initiates IAM credential rotation for a list of users`)... but I keep getting the error in the screenshot.

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/31543/162863964-9695a588-0769-4788-9873-5d0e5bada4a2.png">

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/31543/162864009-44b1cb6a-cff2-47f5-add7-792ca0e9161b.png">

However, I noticed if I play around with `scheduleDuration` I can trigger key rotation, but that requires multiple cdk deployments (setting this param to some arbitrary value in the future initially, and then setting it yo 7 days which will trigger key rotation and custom handler execution).

**Comment by willdady** [comment]
Deleting the credentials from Secrets Manager is not instant.

> Secrets Manager performs the actual deletion with an asynchronous background process, so there might be a short delay before the secret is permanently deleted.

You are likely to run into this error if you set `scheduleDuration` too low as it will be trying to create the secret when it already exists, albeit in a deleting state. Similarly, if you _manually_ invoke the Lambda more than once within a small amount of time you are very likely get that error.

Unfortunately it's unclear on how long it typically takes for the secret to actually be deleted.

**Comment by robertd** [comment]
Thanks for all the help. 👍
